# Generated by Django 4.2.6 on 2023-12-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_variant',
            new_name='color_varient',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_variant',
            new_name='size_varient',
        ),
    ]
