# Generated by Django 4.2.6 on 2023-12-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eamil_token',
            new_name='email_token',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_varified',
            new_name='is_email_verified',
        ),
    ]
